# Generated by Django 4.2.3 on 2023-09-01 20:53

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccount_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='ci',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='full_name',
            field=models.CharField(default='', max_length=355),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='suspend',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='avatar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(error_messages={'unique': 'Nombre de usuario o CI ya existe.'}, max_length=255, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
